version: "3.4"

services:
  locust_master:
    build:
      context: .
    container_name: locustio_master
    ports:
      - 80:8089
    command: locust --master

  locust_slave:
    build:
      context: .
    container_name: locustio_slave
    ports:
      - 8089:8089
    command: locust --master-host=${LOCUST_TARGET_HOST}